Repository e2nIEE/pandapower, pull requests merged in 2021-12, with the labels that each got.

#1416 save numpy objects with signature in JSON encoder
  pandapower/io_utils.py
  pandapower/test/api/test_file_io.py
Labels: fileIO

#1418 Update newtonpf.py: better initialization of slack power
  pandapower/pypower/newtonpf.py
Labels: powerflow

#1422 bugfix fro ther wrong indent in _create_costs
  pandapower/converter/pypower/from_ppc.py
Labels: bug, converter
