Repository e2nIEE/pandapower, pull requests merged in 2022-09, with the labels that each got.

#1696 Tdpf bugfix results
  pandapower/results_branch.py
Labels: bug, powerflow

#1690 add test for distributed slack together with enforce_q_lims
  pandapower/pf/run_newton_raphson_pf.py
  pandapower/test/loadflow/test_dist_slack.py
Labels: powerflow

#1706 update docs
  doc/opf/powermodels.rst
  doc/opf/pypower_run.rst
Labels: OPF, docs/tutorials

#1711 Test dist slack q lims
  pandapower/estimation/results.py
  pandapower/pf/pfsoln_numba.py
  pandapower/pf/run_newton_raphson_pf.py
  pandapower/pypower/pfsoln.py
  pandapower/test/loadflow/test_dist_slack.py
Labels: bug, powerflow

#1708 Feature/opf knwon problems
  doc/opf.rst
  doc/opf/known_problems.rst
  doc/opf/opf_ready_nets.csv
Labels: OPF, docs/tutorials

#1718 update pandas to 1.5: iteritems deprecation; also remove six dependency
  CHANGELOG.rst
  pandapower/auxiliary.py
  pandapower/convert_format.py
  pandapower/grid_equivalents/toolbox.py
  pandapower/io_utils.py
  pandapower/pf/run_bfswpf.py
  pandapower/sql_io.py
  pandapower/test/api/test_diagnostic.py
Labels: compatibility

#1717 bugfix typo
  pandapower/toolbox.py
Labels: bug

#1713 added doc grid_equivalent
  doc/gridequivalent.rst
  doc/gridequivalent/gridequivalent_example.rst
  doc/gridequivalent/gridequivalent_overview.rst
  doc/gridequivalent/run_function.rst
  doc/gridequivalent/tutorials.rst
  doc/index.rst
  doc/pics/gridequivalent/full_case9.png
  doc/pics/gridequivalent/reduced_case9.png
  doc/pics/gridequivalent/res_comparison.png
  doc/pics/gridequivalent/run_geq_overview.png
  doc/pics/gridequivalent/schema_geq.png
  doc/pics/gridequivalent/ward.png
  pandapower/grid_equivalents/auxiliary.py
  pandapower/grid_equivalents/get_equivalent.py
  pandapower/grid_equivalents/rei_generation.py
  pandapower/grid_equivalents/ward_generation.py
  pandapower/test/grid_equivalents/test_get_equivalent.py
  pandapower/test/grid_equivalents/test_grid_equivalents_toolbox.py
  tutorials/grid_equivalents.ipynb
  tutorials/pandamodels_ost.ipynb
Labels: grid_equivalents
