Repository e2nIEE/pandapower, pull requests merged in 2023-05, with the labels that each got.

#2004 bugfix: shape issues when calculating Type "C" short-circuit current
  CHANGELOG.rst
  pandapower/shortcircuit/currents.py
Labels: bug, shortcircuit

#2017 fix bug with old values from AC power flow for results of DC power fl…
  CHANGELOG.rst
  pandapower/results_bus.py
  pandapower/test/loadflow/test_rundcpp.py
Labels: bug, powerflow

#1994 added code, test, and tutorial for loading reduction with pandamodels
  CHANGELOG.rst
  pandapower/runpm.py
  pandapower/test/grid_equivalents/test_get_equivalent.py
  pandapower/test/opf/test_pandamodels_runpm.py
  tutorials/pandamodels_reactive power optimization.ipynb
Labels: PandaModels

#2045 BUGFIX: apply correction factors to gen correctly when there is a gen…
  CHANGELOG.rst
  pandapower/build_bus.py
  pandapower/build_gen.py
  pandapower/pypower/idx_bus_sc.py
  pandapower/pypower/idx_gen.py
  pandapower/shortcircuit/ppc_conversion.py
  pandapower/test/shortcircuit/test_gen.py
Labels: bug, shortcircuit

#2048 small changes for I/O with xlsx
  CHANGELOG.rst
  pandapower/io_utils.py
  pandapower/toolbox/comparison.py
Labels: fileIO

#2052 JSON I/O for MultiIndex + get new index with MultiIndex
  CHANGELOG.rst
  pandapower/auxiliary.py
  pandapower/io_utils.py
  pandapower/test/api/test_file_io.py
Labels: bug, fileIO

#2057 Update github_test_action.yml
  .github/workflows/github_test_action.yml
  .github/workflows/release.yml
  CHANGELOG.rst
Labels: compatibility, dependencies, maintenance
