Repository e2nIEE/pandapower, pull requests merged in 2023-07, with the labels that each got.

#2073 Feature/issue template v2
  .github/ISSUE_TEMPLATE/blank-template.md
  .github/ISSUE_TEMPLATE/blank_template.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  pandapower/plotting/plotly/simple_plotly.py
Labels: enhancement

#2079 always convert RATE_A to ppc
  CHANGELOG.rst
  pandapower/build_branch.py
Labels: compatibility

#2087 Update build_branch.py
  pandapower/build_branch.py
Labels: powerflow, compatibility, converter

#2059 Update of the short-circuit results documentation
  CHANGELOG.rst
  doc/elements/bus.rst
  doc/elements/bus_res_sc.csv
  doc/elements/line.rst
  doc/elements/line_res_sc.csv
  doc/elements/trafo.rst
  doc/elements/trafo3w.rst
  doc/elements/trafo3w_res_sc.csv
  doc/elements/trafo_res_sc.csv
Labels: shortcircuit, docs/tutorials
