Repository e2nIEE/pandapower, pull requests merged in 2023-01, with the labels that each got.

#1814 missing init files in test
  pandapower/test/grid_equivalents/__init__.py
  pandapower/test/plotting/__init__.py
  pandapower/test/test_files/__init__.py
  pandapower/test/topology/__init__.py
Labels: maintenance

#1815 added tests for characteristic
  CHANGELOG.rst
  pandapower/control/util/characteristic.py
  pandapower/control/util/diagnostic.py
  pandapower/test/control/test_tap_dependent_impedance.py
Labels: coverage

#1826 restore multiindex with json fileIO Option 2
  CHANGELOG.rst
  pandapower/convert_format.py
  pandapower/file_io.py
  pandapower/io_utils.py
  pandapower/test/api/test_file_io.py
Labels: fileIO

#1840 Update .readthedocs.yml, install plotting packages
  .readthedocs.yml
Labels: bug, plotting, docs/tutorials

#1845 bugfix for trafo3w tap dependent impedance
  CHANGELOG.rst
  pandapower/create.py
Labels: bug

#1847 bugfix optional columns with pandapower create
  CHANGELOG.rst
  pandapower/create.py
  pandapower/test/api/test_create.py
Labels: bug

#1849 optional columns for TDPF in create lines
  CHANGELOG.rst
  pandapower/create.py
  pandapower/test/api/test_create.py
Labels: docs/tutorials
