Repository e2nIEE/pandapower, pull requests merged in 2024-03, with the labels that each got.

#2230 Fix/sql custom table list
  CHANGELOG.rst
  pandapower/io_utils.py
  pandapower/sql_io.py
Labels: fileIO

#2240 fix lightsim2grid 0.8.0 imports
  .github/workflows/github_test_action.yml
  CHANGELOG.rst
  pandapower/contingency/contingency.py
Labels: bug, compatibility

#2205 [feature] improving speed #2204
  CHANGELOG.rst
  pandapower/auxiliary.py
Labels: powerflow, enhancement

#2243 remove the step to install grid2op together with ls2g - issue fixed i…
  .github/workflows/github_test_action.yml
Labels: compatibility

#2249 enable trafo and switch custom weights
  CHANGELOG.rst
  pandapower/plotting/generic_geodata.py
  pandapower/topology/create_graph.py
Labels: topology
